{"uuid": "3ef7121a-8061-45b0-94ba-4c02534d7962", "children": ["8331a803-5be1-4da8-a111-5ce04738e62a"], "befores": [{"name": "setup_teardown", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 113\nCurrent browser version is 134.0.6998.177 with binary path C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x00428893+48451]\n\t(No symbol) [0x003BB8A1]\n\t(No symbol) [0x002C5058]\n\t(No symbol) [0x002E5D9C]\n\t(No symbol) [0x002E1AA3]\n\t(No symbol) [0x002E0019]\n\t(No symbol) [0x00310798]\n\t(No symbol) [0x0031047C]\n\t(No symbol) [0x0030A0B6]\n\t(No symbol) [0x002E7E08]\n\t(No symbol) [0x002E8F2D]\n\tGetHandleVerifier [0x00688E3A+2540266]\n\tGetHandleVerifier [0x006C8959+2801161]\n\tGetHandleVerifier [0x006C295C+2776588]\n\tGetHandleVerifier [0x004B2280+612144]\n\t(No symbol) [0x003C4F6C]\n\t(No symbol) [0x003C11D8]\n\t(No symbol) [0x003C12BB]\n\t(No symbol) [0x003B4857]\n\tBaseThreadInitThunk [0x75005D49+25]\n\tRtlInitializeExceptionChain [0x7726CE3B+107]\n\tRtlGetAppContainerNamedObjectPath [0x7726CDC1+561]\n\n", "trace": "  File \"D:\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Python39\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"E:\\AutoTest\\FgAIHelp\\tests\\base_test.py\", line 19, in setup_teardown\n    self.driver = webdriver.Chrome()\n  File \"D:\\Python39\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"D:\\Python39\\lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 66, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"D:\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 250, in __init__\n    self.start_session(capabilities)\n  File \"D:\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 342, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"D:\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Python39\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1744360551140, "stop": 1744360555191}], "start": 1744360551140, "stop": 1744360555276}